# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon-180x180.png"
    high_res_favicon: "/img/favicon-180x180.png"
    apple_touch_icon: "/img/favicon-180x180.png"
    keywords: tiny calf

Intro:
    name: Tiny Calf
    slogan: "do something awesome"
    HeadButton: TINY CALF
    mainlogo: http://ow3lvmu74.bkt.clouddn.com/images/MainLogo.png

Nav:
    Home_name: 主页
    is_use_categories : false
    categories_name: 分类
    is_use_archives : false
    archives_name: 归档
    icon:
        github:
            use: true
            link: https://github.com/TinyCalf
        Twitter:
            use: false
            link:
        Facebook:
            use: false
            link:
        Instagram:
            use: false
            link:
        Wechat:
            use: true
            link:
        QQ:
            use: true
            link:
        Email:
            use: true
            link:
    pages:
        # 简历:
        #     link: "/about/"
        # 团队 :
        #     link: "/group/"
        # 图库 :
        #     link: "/gallery/"
        区块链:
            link: "/categories/区块链/"
        Linux:
            link: "/categories/Linux/"
        Nodejs:
            link: "/categories/nodejs/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: 欢迎来 Tiny Calf
    description: 区块链研究小站，只谈技术，不谈token
    pic_url: http://ow3lvmu74.bkt.clouddn.com/images/me.jpg
    goto_ulr: ""

Gallery :
    title: Mr.metro
    description: Just another fine responsive

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染
# default dark funky okaidia twilight coy solarized  可选项
# link to review : http://prismjs.com/index.html   官网预览
prism: tinycalf

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: changyan
    shortname: tinycalf
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid: cytdxLe3B
    changyan_conf: fa28a0faa37516b9a4d5ef03d78d65b2
    changyan_thread_key_type: path

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
    swiftype_key: Just another fine responsive


# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "/js/busuanzi.min.js"
